---

riemann:
  image: riemann
  ports:
    - "5555:5555"
    - "5555:5555/udp"
    - "5556:5556"
  links:
    - influxdb

riemann-dash:
  image: riemann-dash
  ports:
    - "4567:4567"

influxdb:
  image: influxdb
  volumes:
    - riemann-influxdb-lib:/var/lib/influxdb

grafana:
  image: grafana/grafana
  volumes:
    - riemann-grafana-lib:/var/lib/grafana
    - riemann-grafana-etc:/etc/grafana
    - riemann-grafana-log:/var/log/grafana
  ports:
    - "3000:3000"
  links:
    - influxdb
